// Import the functions you need from the SDKs you need
import { initializeApp } from "firebase/app";
// TODO: Add SDKs for Firebase products that you want to use
// https://firebase.google.com/docs/web/setup#available-libraries

// Your web app's Firebase configuration
const firebaseConfig = {
  apiKey: "AIzaSyDsCssYOfliqkOnBpqB0-eJQnEPth_CN6E",
  authDomain: "database-1-a51f0.firebaseapp.com",
  projectId: "database-1-a51f0",
  storageBucket: "database-1-a51f0.appspot.com",
  messagingSenderId: "811082524467",
  appId: "1:811082524467:web:5d18cb6bff004c1040c046",
};

// Initialize Firebase
const app = initializeApp(firebaseConfig);
